### ISSUE TITLE
[Add Map] Retarded Defense: Ravana

### ISSUE THREAD

**Issue by Redeemer21** [MahBoiDeveloper/RedAlert3World#1]
### Map Name

[Retarded Defense: Ravana]

### Map Kind

Art Of Defense

### Author

TheGunrun

### Author Contact

(https://www.cnclabs.com/downloads/details.aspx?id=520)

### Download Link

https://www.cnclabs.com/downloads/downloader.aspx?id=520

**Comment by MahBoiDeveloper** [comment]
Mission actually is tower defense

**Comment by MahBoiDeveloper** [comment]
Add by 1c965248b409794e8397694e7f25606b184a2669 commit.
