### ISSUE TITLE
[Add Map] Mission operations：Shivery_Carafia

### ISSUE THREAD

**Issue by Redeemer21** [MahBoiDeveloper/RedAlert3World#48]
### Map Name

Mission operations：Shivery_Carafia

### Map Kind

Cooperative Mission

### Author

[Mirrar-x]

### Author Contact

(https://www.moddb.com/members/mirrar-x)

### Download Link

https://www.moddb.com/games/cc-red-alert-3/addons/mission-operationsshivery-carafia

**Comment by MahBoiDeveloper** [comment]
Added by b88b74548f3b763b71b40d97ca358b5995fcf944.
