### ISSUE TITLE
[Add Map] Mission Imperor v 1.4

### ISSUE THREAD

**Issue by Redeemer21** [MahBoiDeveloper/RedAlert3World#49]
### Map Name

Mission Imperor v 1.4

### Map Kind

Cooperative Mission

### Author

666pro

### Author Contact

(https://www.moddb.com/games/cc-red-alert-3/addons?filter=t&licence=3)

### Download Link

https://www.moddb.com/games/cc-red-alert-3/addons/mission-imperor1

**Comment by MahBoiDeveloper** [comment]
Added by 4efb300f3cc6e69f6ef99b732579d333d8d50f4e.
