### ISSUE TITLE
[Add Map] TD - A New Hope Map

### ISSUE THREAD

**Issue by Redeemer21** [MahBoiDeveloper/RedAlert3World#50]
### Map Name

TD - A New Hope Map

### Map Kind

Tower Defense

### Author

[Oriode]

### Author Contact

(https://www.moddb.com/members/oriode)

### Download Link

https://www.moddb.com/games/cc-red-alert-3/addons/td-a-new-hope-map

**Comment by MahBoiDeveloper** [comment]
Added by da98a15737bc2c6cc54dd9c30fa360e88fef31b1.
