### ISSUE TITLE
[Add Map] The_Final_Chance

### ISSUE THREAD

**Issue by Redeemer21** [MahBoiDeveloper/RedAlert3World#51]
### Map Name

The_Final_Chance

### Map Kind

Singleplayer Mission

### Author

[Mirrar-x]

### Author Contact

(https://www.moddb.com/members/mirrar-x)

### Download Link

https://www.moddb.com/games/cc-red-alert-3/addons/miathe-final-chance

**Comment by MahBoiDeveloper** [comment]
Added by 7ae22d35368de9288c6b38feed5297c6c0e485bb.
