### ISSUE TITLE
[Add Map] C&C: Red Alert 3 Singleplayer Maps Source

### ISSUE THREAD

**Issue by Redeemer21** [MahBoiDeveloper/RedAlert3World#52]
### Map Name

C&C: Red Alert 3 Singleplayer Maps Source

### Map Kind

Singleplayer Mission

### Author

[Plokite_Wolf]

### Author Contact

(https://www.moddb.com/members/plokite-wolf)

### Download Link

https://www.moddb.com/games/cc-red-alert-3/addons/cc-red-alert-3-singleplayer-maps-source

**Comment by MahBoiDeveloper** [comment]
This maps doesn't suppose to play through skirmish.
