### ISSUE TITLE
[Add Map] (LDS PVE) Bloody Blade Revenge

### ISSUE THREAD

**Issue by Redeemer21** [MahBoiDeveloper/RedAlert3World#53]
### Map Name

(LDS PVE) Bloody Blade Revenge

### Map Kind

Cooperative Mission

### Author

[Little_dream]

### Author Contact

(https://www.moddb.com/members/little-dream)

### Download Link

https://www.moddb.com/games/cc-red-alert-3/addons/lds-pve-bloody-blade-revenge

**Comment by MahBoiDeveloper** [comment]
Done by 94dc7e6.
