### ISSUE TITLE
[Add Map] Bad Cargo

### ISSUE THREAD

**Issue by Redeemer21** [MahBoiDeveloper/RedAlert3World#54]
### Map Name

Bad Cargo

### Map Kind

Cooperative Mission

### Author

[Wichilie]

### Author Contact

(https://www.moddb.com/members/wichilie)

### Download Link

https://www.moddb.com/games/cc-red-alert-3/addons/bad-cargo

**Comment by MahBoiDeveloper** [comment]
This is Skirmish PVP map, not a mission. coop, challenge, AOD.
